// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.8
// 	protoc        v6.33.4
// source: config/v1/config.proto

package configpb

import (
	_ "google.golang.org/genproto/googleapis/api/annotations"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	timestamppb "google.golang.org/protobuf/types/known/timestamppb"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// WriteMode specifies how Set should handle existing entries.
type WriteMode int32

const (
	WriteMode_WRITE_MODE_UNSPECIFIED WriteMode = 0
	WriteMode_WRITE_MODE_UPSERT      WriteMode = 1 // Create or update (default)
	WriteMode_WRITE_MODE_CREATE      WriteMode = 2 // Create only, fail if exists
	WriteMode_WRITE_MODE_UPDATE      WriteMode = 3 // Update only, fail if not exists
)

// Enum value maps for WriteMode.
var (
	WriteMode_name = map[int32]string{
		0: "WRITE_MODE_UNSPECIFIED",
		1: "WRITE_MODE_UPSERT",
		2: "WRITE_MODE_CREATE",
		3: "WRITE_MODE_UPDATE",
	}
	WriteMode_value = map[string]int32{
		"WRITE_MODE_UNSPECIFIED": 0,
		"WRITE_MODE_UPSERT":      1,
		"WRITE_MODE_CREATE":      2,
		"WRITE_MODE_UPDATE":      3,
	}
)

func (x WriteMode) Enum() *WriteMode {
	p := new(WriteMode)
	*p = x
	return p
}

func (x WriteMode) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (WriteMode) Descriptor() protoreflect.EnumDescriptor {
	return file_config_v1_config_proto_enumTypes[0].Descriptor()
}

func (WriteMode) Type() protoreflect.EnumType {
	return &file_config_v1_config_proto_enumTypes[0]
}

func (x WriteMode) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use WriteMode.Descriptor instead.
func (WriteMode) EnumDescriptor() ([]byte, []int) {
	return file_config_v1_config_proto_rawDescGZIP(), []int{0}
}

// ChangeType indicates the type of configuration change.
type ChangeType int32

const (
	ChangeType_CHANGE_TYPE_UNSPECIFIED  ChangeType = 0
	ChangeType_CHANGE_TYPE_SET          ChangeType = 1
	ChangeType_CHANGE_TYPE_DELETE       ChangeType = 2
	ChangeType_CHANGE_TYPE_ALIAS_SET    ChangeType = 3
	ChangeType_CHANGE_TYPE_ALIAS_DELETE ChangeType = 4
)

// Enum value maps for ChangeType.
var (
	ChangeType_name = map[int32]string{
		0: "CHANGE_TYPE_UNSPECIFIED",
		1: "CHANGE_TYPE_SET",
		2: "CHANGE_TYPE_DELETE",
		3: "CHANGE_TYPE_ALIAS_SET",
		4: "CHANGE_TYPE_ALIAS_DELETE",
	}
	ChangeType_value = map[string]int32{
		"CHANGE_TYPE_UNSPECIFIED":  0,
		"CHANGE_TYPE_SET":          1,
		"CHANGE_TYPE_DELETE":       2,
		"CHANGE_TYPE_ALIAS_SET":    3,
		"CHANGE_TYPE_ALIAS_DELETE": 4,
	}
)

func (x ChangeType) Enum() *ChangeType {
	p := new(ChangeType)
	*p = x
	return p
}

func (x ChangeType) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (ChangeType) Descriptor() protoreflect.EnumDescriptor {
	return file_config_v1_config_proto_enumTypes[1].Descriptor()
}

func (ChangeType) Type() protoreflect.EnumType {
	return &file_config_v1_config_proto_enumTypes[1]
}

func (x ChangeType) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use ChangeType.Descriptor instead.
func (ChangeType) EnumDescriptor() ([]byte, []int) {
	return file_config_v1_config_proto_rawDescGZIP(), []int{1}
}

// GetRequest is the request for Get.
type GetRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Namespace     string                 `protobuf:"bytes,1,opt,name=namespace,proto3" json:"namespace,omitempty"`
	Key           string                 `protobuf:"bytes,2,opt,name=key,proto3" json:"key,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetRequest) Reset() {
	*x = GetRequest{}
	mi := &file_config_v1_config_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetRequest) ProtoMessage() {}

func (x *GetRequest) ProtoReflect() protoreflect.Message {
	mi := &file_config_v1_config_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetRequest.ProtoReflect.Descriptor instead.
func (*GetRequest) Descriptor() ([]byte, []int) {
	return file_config_v1_config_proto_rawDescGZIP(), []int{0}
}

func (x *GetRequest) GetNamespace() string {
	if x != nil {
		return x.Namespace
	}
	return ""
}

func (x *GetRequest) GetKey() string {
	if x != nil {
		return x.Key
	}
	return ""
}

// GetResponse is the response for Get.
type GetResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Entry         *Entry                 `protobuf:"bytes,1,opt,name=entry,proto3" json:"entry,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetResponse) Reset() {
	*x = GetResponse{}
	mi := &file_config_v1_config_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetResponse) ProtoMessage() {}

func (x *GetResponse) ProtoReflect() protoreflect.Message {
	mi := &file_config_v1_config_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetResponse.ProtoReflect.Descriptor instead.
func (*GetResponse) Descriptor() ([]byte, []int) {
	return file_config_v1_config_proto_rawDescGZIP(), []int{1}
}

func (x *GetResponse) GetEntry() *Entry {
	if x != nil {
		return x.Entry
	}
	return nil
}

// SetRequest is the request for Set.
type SetRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Namespace     string                 `protobuf:"bytes,1,opt,name=namespace,proto3" json:"namespace,omitempty"`
	Key           string                 `protobuf:"bytes,2,opt,name=key,proto3" json:"key,omitempty"`
	Value         []byte                 `protobuf:"bytes,3,opt,name=value,proto3" json:"value,omitempty"`
	Codec         string                 `protobuf:"bytes,4,opt,name=codec,proto3" json:"codec,omitempty"`                                                    // "json", "yaml", "toml" - defaults to "json"
	WriteMode     WriteMode              `protobuf:"varint,5,opt,name=write_mode,json=writeMode,proto3,enum=config.v1.WriteMode" json:"write_mode,omitempty"` // Defaults to UPSERT
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SetRequest) Reset() {
	*x = SetRequest{}
	mi := &file_config_v1_config_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SetRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SetRequest) ProtoMessage() {}

func (x *SetRequest) ProtoReflect() protoreflect.Message {
	mi := &file_config_v1_config_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SetRequest.ProtoReflect.Descriptor instead.
func (*SetRequest) Descriptor() ([]byte, []int) {
	return file_config_v1_config_proto_rawDescGZIP(), []int{2}
}

func (x *SetRequest) GetNamespace() string {
	if x != nil {
		return x.Namespace
	}
	return ""
}

func (x *SetRequest) GetKey() string {
	if x != nil {
		return x.Key
	}
	return ""
}

func (x *SetRequest) GetValue() []byte {
	if x != nil {
		return x.Value
	}
	return nil
}

func (x *SetRequest) GetCodec() string {
	if x != nil {
		return x.Codec
	}
	return ""
}

func (x *SetRequest) GetWriteMode() WriteMode {
	if x != nil {
		return x.WriteMode
	}
	return WriteMode_WRITE_MODE_UNSPECIFIED
}

// SetResponse is the response for Set.
type SetResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Entry         *Entry                 `protobuf:"bytes,1,opt,name=entry,proto3" json:"entry,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SetResponse) Reset() {
	*x = SetResponse{}
	mi := &file_config_v1_config_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SetResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SetResponse) ProtoMessage() {}

func (x *SetResponse) ProtoReflect() protoreflect.Message {
	mi := &file_config_v1_config_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SetResponse.ProtoReflect.Descriptor instead.
func (*SetResponse) Descriptor() ([]byte, []int) {
	return file_config_v1_config_proto_rawDescGZIP(), []int{3}
}

func (x *SetResponse) GetEntry() *Entry {
	if x != nil {
		return x.Entry
	}
	return nil
}

// DeleteRequest is the request for Delete.
type DeleteRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Namespace     string                 `protobuf:"bytes,1,opt,name=namespace,proto3" json:"namespace,omitempty"`
	Key           string                 `protobuf:"bytes,2,opt,name=key,proto3" json:"key,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DeleteRequest) Reset() {
	*x = DeleteRequest{}
	mi := &file_config_v1_config_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DeleteRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeleteRequest) ProtoMessage() {}

func (x *DeleteRequest) ProtoReflect() protoreflect.Message {
	mi := &file_config_v1_config_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeleteRequest.ProtoReflect.Descriptor instead.
func (*DeleteRequest) Descriptor() ([]byte, []int) {
	return file_config_v1_config_proto_rawDescGZIP(), []int{4}
}

func (x *DeleteRequest) GetNamespace() string {
	if x != nil {
		return x.Namespace
	}
	return ""
}

func (x *DeleteRequest) GetKey() string {
	if x != nil {
		return x.Key
	}
	return ""
}

// DeleteResponse is the response for Delete.
type DeleteResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DeleteResponse) Reset() {
	*x = DeleteResponse{}
	mi := &file_config_v1_config_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DeleteResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeleteResponse) ProtoMessage() {}

func (x *DeleteResponse) ProtoReflect() protoreflect.Message {
	mi := &file_config_v1_config_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeleteResponse.ProtoReflect.Descriptor instead.
func (*DeleteResponse) Descriptor() ([]byte, []int) {
	return file_config_v1_config_proto_rawDescGZIP(), []int{5}
}

// ListRequest is the request for List.
type ListRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Namespace     string                 `protobuf:"bytes,1,opt,name=namespace,proto3" json:"namespace,omitempty"`
	Prefix        string                 `protobuf:"bytes,2,opt,name=prefix,proto3" json:"prefix,omitempty"` // Key prefix filter (empty = all keys)
	Limit         int32                  `protobuf:"varint,3,opt,name=limit,proto3" json:"limit,omitempty"`  // Max results (0 = server default)
	Cursor        string                 `protobuf:"bytes,4,opt,name=cursor,proto3" json:"cursor,omitempty"` // Pagination cursor from previous response
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListRequest) Reset() {
	*x = ListRequest{}
	mi := &file_config_v1_config_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListRequest) ProtoMessage() {}

func (x *ListRequest) ProtoReflect() protoreflect.Message {
	mi := &file_config_v1_config_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListRequest.ProtoReflect.Descriptor instead.
func (*ListRequest) Descriptor() ([]byte, []int) {
	return file_config_v1_config_proto_rawDescGZIP(), []int{6}
}

func (x *ListRequest) GetNamespace() string {
	if x != nil {
		return x.Namespace
	}
	return ""
}

func (x *ListRequest) GetPrefix() string {
	if x != nil {
		return x.Prefix
	}
	return ""
}

func (x *ListRequest) GetLimit() int32 {
	if x != nil {
		return x.Limit
	}
	return 0
}

func (x *ListRequest) GetCursor() string {
	if x != nil {
		return x.Cursor
	}
	return ""
}

// ListResponse is the response for List.
type ListResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Entries       []*Entry               `protobuf:"bytes,1,rep,name=entries,proto3" json:"entries,omitempty"`
	NextCursor    string                 `protobuf:"bytes,2,opt,name=next_cursor,json=nextCursor,proto3" json:"next_cursor,omitempty"` // Empty if no more results
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListResponse) Reset() {
	*x = ListResponse{}
	mi := &file_config_v1_config_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListResponse) ProtoMessage() {}

func (x *ListResponse) ProtoReflect() protoreflect.Message {
	mi := &file_config_v1_config_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListResponse.ProtoReflect.Descriptor instead.
func (*ListResponse) Descriptor() ([]byte, []int) {
	return file_config_v1_config_proto_rawDescGZIP(), []int{7}
}

func (x *ListResponse) GetEntries() []*Entry {
	if x != nil {
		return x.Entries
	}
	return nil
}

func (x *ListResponse) GetNextCursor() string {
	if x != nil {
		return x.NextCursor
	}
	return ""
}

// GetVersionsRequest is the request for GetVersions.
type GetVersionsRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Namespace     string                 `protobuf:"bytes,1,opt,name=namespace,proto3" json:"namespace,omitempty"`
	Key           string                 `protobuf:"bytes,2,opt,name=key,proto3" json:"key,omitempty"`
	Version       int64                  `protobuf:"varint,3,opt,name=version,proto3" json:"version,omitempty"` // Specific version to retrieve (0 = all versions)
	Limit         int32                  `protobuf:"varint,4,opt,name=limit,proto3" json:"limit,omitempty"`     // Max results (0 = server default)
	Cursor        string                 `protobuf:"bytes,5,opt,name=cursor,proto3" json:"cursor,omitempty"`    // Pagination cursor from previous response
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetVersionsRequest) Reset() {
	*x = GetVersionsRequest{}
	mi := &file_config_v1_config_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetVersionsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetVersionsRequest) ProtoMessage() {}

func (x *GetVersionsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_config_v1_config_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetVersionsRequest.ProtoReflect.Descriptor instead.
func (*GetVersionsRequest) Descriptor() ([]byte, []int) {
	return file_config_v1_config_proto_rawDescGZIP(), []int{8}
}

func (x *GetVersionsRequest) GetNamespace() string {
	if x != nil {
		return x.Namespace
	}
	return ""
}

func (x *GetVersionsRequest) GetKey() string {
	if x != nil {
		return x.Key
	}
	return ""
}

func (x *GetVersionsRequest) GetVersion() int64 {
	if x != nil {
		return x.Version
	}
	return 0
}

func (x *GetVersionsRequest) GetLimit() int32 {
	if x != nil {
		return x.Limit
	}
	return 0
}

func (x *GetVersionsRequest) GetCursor() string {
	if x != nil {
		return x.Cursor
	}
	return ""
}

// GetVersionsResponse is the response for GetVersions.
type GetVersionsResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Entries       []*Entry               `protobuf:"bytes,1,rep,name=entries,proto3" json:"entries,omitempty"`                         // Versions ordered by version descending
	NextCursor    string                 `protobuf:"bytes,2,opt,name=next_cursor,json=nextCursor,proto3" json:"next_cursor,omitempty"` // Empty if no more results
	Limit         int32                  `protobuf:"varint,3,opt,name=limit,proto3" json:"limit,omitempty"`                            // Actual limit used
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetVersionsResponse) Reset() {
	*x = GetVersionsResponse{}
	mi := &file_config_v1_config_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetVersionsResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetVersionsResponse) ProtoMessage() {}

func (x *GetVersionsResponse) ProtoReflect() protoreflect.Message {
	mi := &file_config_v1_config_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetVersionsResponse.ProtoReflect.Descriptor instead.
func (*GetVersionsResponse) Descriptor() ([]byte, []int) {
	return file_config_v1_config_proto_rawDescGZIP(), []int{9}
}

func (x *GetVersionsResponse) GetEntries() []*Entry {
	if x != nil {
		return x.Entries
	}
	return nil
}

func (x *GetVersionsResponse) GetNextCursor() string {
	if x != nil {
		return x.NextCursor
	}
	return ""
}

func (x *GetVersionsResponse) GetLimit() int32 {
	if x != nil {
		return x.Limit
	}
	return 0
}

// SnapshotRequest is the request for Snapshot.
type SnapshotRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Namespace     string                 `protobuf:"bytes,1,opt,name=namespace,proto3" json:"namespace,omitempty"`
	IfNoneMatch   string                 `protobuf:"bytes,2,opt,name=if_none_match,json=ifNoneMatch,proto3" json:"if_none_match,omitempty"` // ETag from previous snapshot (empty = always return)
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SnapshotRequest) Reset() {
	*x = SnapshotRequest{}
	mi := &file_config_v1_config_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SnapshotRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SnapshotRequest) ProtoMessage() {}

func (x *SnapshotRequest) ProtoReflect() protoreflect.Message {
	mi := &file_config_v1_config_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SnapshotRequest.ProtoReflect.Descriptor instead.
func (*SnapshotRequest) Descriptor() ([]byte, []int) {
	return file_config_v1_config_proto_rawDescGZIP(), []int{10}
}

func (x *SnapshotRequest) GetNamespace() string {
	if x != nil {
		return x.Namespace
	}
	return ""
}

func (x *SnapshotRequest) GetIfNoneMatch() string {
	if x != nil {
		return x.IfNoneMatch
	}
	return ""
}

// SnapshotResponse is the response for Snapshot.
type SnapshotResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Entries       []*Entry               `protobuf:"bytes,1,rep,name=entries,proto3" json:"entries,omitempty"`
	Etag          string                 `protobuf:"bytes,2,opt,name=etag,proto3" json:"etag,omitempty"`                                   // Opaque version identifier for caching
	NotModified   bool                   `protobuf:"varint,3,opt,name=not_modified,json=notModified,proto3" json:"not_modified,omitempty"` // True if if_none_match matched (entries will be empty)
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SnapshotResponse) Reset() {
	*x = SnapshotResponse{}
	mi := &file_config_v1_config_proto_msgTypes[11]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SnapshotResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SnapshotResponse) ProtoMessage() {}

func (x *SnapshotResponse) ProtoReflect() protoreflect.Message {
	mi := &file_config_v1_config_proto_msgTypes[11]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SnapshotResponse.ProtoReflect.Descriptor instead.
func (*SnapshotResponse) Descriptor() ([]byte, []int) {
	return file_config_v1_config_proto_rawDescGZIP(), []int{11}
}

func (x *SnapshotResponse) GetEntries() []*Entry {
	if x != nil {
		return x.Entries
	}
	return nil
}

func (x *SnapshotResponse) GetEtag() string {
	if x != nil {
		return x.Etag
	}
	return ""
}

func (x *SnapshotResponse) GetNotModified() bool {
	if x != nil {
		return x.NotModified
	}
	return false
}

// WatchRequest is the request for Watch.
type WatchRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Namespaces    []string               `protobuf:"bytes,1,rep,name=namespaces,proto3" json:"namespaces,omitempty"` // Namespaces to watch (empty = all)
	Prefixes      []string               `protobuf:"bytes,2,rep,name=prefixes,proto3" json:"prefixes,omitempty"`     // Key prefixes to watch (empty = all)
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *WatchRequest) Reset() {
	*x = WatchRequest{}
	mi := &file_config_v1_config_proto_msgTypes[12]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *WatchRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*WatchRequest) ProtoMessage() {}

func (x *WatchRequest) ProtoReflect() protoreflect.Message {
	mi := &file_config_v1_config_proto_msgTypes[12]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use WatchRequest.ProtoReflect.Descriptor instead.
func (*WatchRequest) Descriptor() ([]byte, []int) {
	return file_config_v1_config_proto_rawDescGZIP(), []int{12}
}

func (x *WatchRequest) GetNamespaces() []string {
	if x != nil {
		return x.Namespaces
	}
	return nil
}

func (x *WatchRequest) GetPrefixes() []string {
	if x != nil {
		return x.Prefixes
	}
	return nil
}

// WatchResponse is a streaming response for Watch.
type WatchResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Type          ChangeType             `protobuf:"varint,1,opt,name=type,proto3,enum=config.v1.ChangeType" json:"type,omitempty"`
	Entry         *Entry                 `protobuf:"bytes,2,opt,name=entry,proto3" json:"entry,omitempty"` // Present for SET, may be minimal for DELETE
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *WatchResponse) Reset() {
	*x = WatchResponse{}
	mi := &file_config_v1_config_proto_msgTypes[13]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *WatchResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*WatchResponse) ProtoMessage() {}

func (x *WatchResponse) ProtoReflect() protoreflect.Message {
	mi := &file_config_v1_config_proto_msgTypes[13]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use WatchResponse.ProtoReflect.Descriptor instead.
func (*WatchResponse) Descriptor() ([]byte, []int) {
	return file_config_v1_config_proto_rawDescGZIP(), []int{13}
}

func (x *WatchResponse) GetType() ChangeType {
	if x != nil {
		return x.Type
	}
	return ChangeType_CHANGE_TYPE_UNSPECIFIED
}

func (x *WatchResponse) GetEntry() *Entry {
	if x != nil {
		return x.Entry
	}
	return nil
}

// CheckAccessRequest is the request for CheckAccess.
type CheckAccessRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Namespace     string                 `protobuf:"bytes,1,opt,name=namespace,proto3" json:"namespace,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CheckAccessRequest) Reset() {
	*x = CheckAccessRequest{}
	mi := &file_config_v1_config_proto_msgTypes[14]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CheckAccessRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CheckAccessRequest) ProtoMessage() {}

func (x *CheckAccessRequest) ProtoReflect() protoreflect.Message {
	mi := &file_config_v1_config_proto_msgTypes[14]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CheckAccessRequest.ProtoReflect.Descriptor instead.
func (*CheckAccessRequest) Descriptor() ([]byte, []int) {
	return file_config_v1_config_proto_rawDescGZIP(), []int{14}
}

func (x *CheckAccessRequest) GetNamespace() string {
	if x != nil {
		return x.Namespace
	}
	return ""
}

// CheckAccessResponse is the response for CheckAccess.
// For HTTP HEAD requests, access level is returned in X-Access-Level header.
type CheckAccessResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	CanRead       bool                   `protobuf:"varint,1,opt,name=can_read,json=canRead,proto3" json:"can_read,omitempty"`
	CanWrite      bool                   `protobuf:"varint,2,opt,name=can_write,json=canWrite,proto3" json:"can_write,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CheckAccessResponse) Reset() {
	*x = CheckAccessResponse{}
	mi := &file_config_v1_config_proto_msgTypes[15]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CheckAccessResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CheckAccessResponse) ProtoMessage() {}

func (x *CheckAccessResponse) ProtoReflect() protoreflect.Message {
	mi := &file_config_v1_config_proto_msgTypes[15]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CheckAccessResponse.ProtoReflect.Descriptor instead.
func (*CheckAccessResponse) Descriptor() ([]byte, []int) {
	return file_config_v1_config_proto_rawDescGZIP(), []int{15}
}

func (x *CheckAccessResponse) GetCanRead() bool {
	if x != nil {
		return x.CanRead
	}
	return false
}

func (x *CheckAccessResponse) GetCanWrite() bool {
	if x != nil {
		return x.CanWrite
	}
	return false
}

// SetAliasRequest is the request for SetAlias.
type SetAliasRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Alias         string                 `protobuf:"bytes,1,opt,name=alias,proto3" json:"alias,omitempty"`   // The alias key name
	Target        string                 `protobuf:"bytes,2,opt,name=target,proto3" json:"target,omitempty"` // The canonical target key name
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SetAliasRequest) Reset() {
	*x = SetAliasRequest{}
	mi := &file_config_v1_config_proto_msgTypes[16]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SetAliasRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SetAliasRequest) ProtoMessage() {}

func (x *SetAliasRequest) ProtoReflect() protoreflect.Message {
	mi := &file_config_v1_config_proto_msgTypes[16]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SetAliasRequest.ProtoReflect.Descriptor instead.
func (*SetAliasRequest) Descriptor() ([]byte, []int) {
	return file_config_v1_config_proto_rawDescGZIP(), []int{16}
}

func (x *SetAliasRequest) GetAlias() string {
	if x != nil {
		return x.Alias
	}
	return ""
}

func (x *SetAliasRequest) GetTarget() string {
	if x != nil {
		return x.Target
	}
	return ""
}

// SetAliasResponse is the response for SetAlias.
type SetAliasResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Alias         *Alias                 `protobuf:"bytes,1,opt,name=alias,proto3" json:"alias,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SetAliasResponse) Reset() {
	*x = SetAliasResponse{}
	mi := &file_config_v1_config_proto_msgTypes[17]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SetAliasResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SetAliasResponse) ProtoMessage() {}

func (x *SetAliasResponse) ProtoReflect() protoreflect.Message {
	mi := &file_config_v1_config_proto_msgTypes[17]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SetAliasResponse.ProtoReflect.Descriptor instead.
func (*SetAliasResponse) Descriptor() ([]byte, []int) {
	return file_config_v1_config_proto_rawDescGZIP(), []int{17}
}

func (x *SetAliasResponse) GetAlias() *Alias {
	if x != nil {
		return x.Alias
	}
	return nil
}

// DeleteAliasRequest is the request for DeleteAlias.
type DeleteAliasRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Alias         string                 `protobuf:"bytes,1,opt,name=alias,proto3" json:"alias,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DeleteAliasRequest) Reset() {
	*x = DeleteAliasRequest{}
	mi := &file_config_v1_config_proto_msgTypes[18]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DeleteAliasRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeleteAliasRequest) ProtoMessage() {}

func (x *DeleteAliasRequest) ProtoReflect() protoreflect.Message {
	mi := &file_config_v1_config_proto_msgTypes[18]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeleteAliasRequest.ProtoReflect.Descriptor instead.
func (*DeleteAliasRequest) Descriptor() ([]byte, []int) {
	return file_config_v1_config_proto_rawDescGZIP(), []int{18}
}

func (x *DeleteAliasRequest) GetAlias() string {
	if x != nil {
		return x.Alias
	}
	return ""
}

// DeleteAliasResponse is the response for DeleteAlias.
type DeleteAliasResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DeleteAliasResponse) Reset() {
	*x = DeleteAliasResponse{}
	mi := &file_config_v1_config_proto_msgTypes[19]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DeleteAliasResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeleteAliasResponse) ProtoMessage() {}

func (x *DeleteAliasResponse) ProtoReflect() protoreflect.Message {
	mi := &file_config_v1_config_proto_msgTypes[19]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeleteAliasResponse.ProtoReflect.Descriptor instead.
func (*DeleteAliasResponse) Descriptor() ([]byte, []int) {
	return file_config_v1_config_proto_rawDescGZIP(), []int{19}
}

// GetAliasRequest is the request for GetAlias.
type GetAliasRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Alias         string                 `protobuf:"bytes,1,opt,name=alias,proto3" json:"alias,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetAliasRequest) Reset() {
	*x = GetAliasRequest{}
	mi := &file_config_v1_config_proto_msgTypes[20]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetAliasRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetAliasRequest) ProtoMessage() {}

func (x *GetAliasRequest) ProtoReflect() protoreflect.Message {
	mi := &file_config_v1_config_proto_msgTypes[20]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetAliasRequest.ProtoReflect.Descriptor instead.
func (*GetAliasRequest) Descriptor() ([]byte, []int) {
	return file_config_v1_config_proto_rawDescGZIP(), []int{20}
}

func (x *GetAliasRequest) GetAlias() string {
	if x != nil {
		return x.Alias
	}
	return ""
}

// GetAliasResponse is the response for GetAlias.
type GetAliasResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Alias         *Alias                 `protobuf:"bytes,1,opt,name=alias,proto3" json:"alias,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetAliasResponse) Reset() {
	*x = GetAliasResponse{}
	mi := &file_config_v1_config_proto_msgTypes[21]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetAliasResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetAliasResponse) ProtoMessage() {}

func (x *GetAliasResponse) ProtoReflect() protoreflect.Message {
	mi := &file_config_v1_config_proto_msgTypes[21]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetAliasResponse.ProtoReflect.Descriptor instead.
func (*GetAliasResponse) Descriptor() ([]byte, []int) {
	return file_config_v1_config_proto_rawDescGZIP(), []int{21}
}

func (x *GetAliasResponse) GetAlias() *Alias {
	if x != nil {
		return x.Alias
	}
	return nil
}

// ListAliasesRequest is the request for ListAliases.
type ListAliasesRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListAliasesRequest) Reset() {
	*x = ListAliasesRequest{}
	mi := &file_config_v1_config_proto_msgTypes[22]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListAliasesRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListAliasesRequest) ProtoMessage() {}

func (x *ListAliasesRequest) ProtoReflect() protoreflect.Message {
	mi := &file_config_v1_config_proto_msgTypes[22]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListAliasesRequest.ProtoReflect.Descriptor instead.
func (*ListAliasesRequest) Descriptor() ([]byte, []int) {
	return file_config_v1_config_proto_rawDescGZIP(), []int{22}
}

// ListAliasesResponse is the response for ListAliases.
type ListAliasesResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Aliases       []*Alias               `protobuf:"bytes,1,rep,name=aliases,proto3" json:"aliases,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListAliasesResponse) Reset() {
	*x = ListAliasesResponse{}
	mi := &file_config_v1_config_proto_msgTypes[23]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListAliasesResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListAliasesResponse) ProtoMessage() {}

func (x *ListAliasesResponse) ProtoReflect() protoreflect.Message {
	mi := &file_config_v1_config_proto_msgTypes[23]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListAliasesResponse.ProtoReflect.Descriptor instead.
func (*ListAliasesResponse) Descriptor() ([]byte, []int) {
	return file_config_v1_config_proto_rawDescGZIP(), []int{23}
}

func (x *ListAliasesResponse) GetAliases() []*Alias {
	if x != nil {
		return x.Aliases
	}
	return nil
}

// Alias represents a key alias mapping.
type Alias struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Alias         string                 `protobuf:"bytes,1,opt,name=alias,proto3" json:"alias,omitempty"`   // The alias key name
	Target        string                 `protobuf:"bytes,2,opt,name=target,proto3" json:"target,omitempty"` // The canonical target key name
	Version       int64                  `protobuf:"varint,3,opt,name=version,proto3" json:"version,omitempty"`
	CreatedAt     *timestamppb.Timestamp `protobuf:"bytes,4,opt,name=created_at,json=createdAt,proto3" json:"created_at,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Alias) Reset() {
	*x = Alias{}
	mi := &file_config_v1_config_proto_msgTypes[24]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Alias) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Alias) ProtoMessage() {}

func (x *Alias) ProtoReflect() protoreflect.Message {
	mi := &file_config_v1_config_proto_msgTypes[24]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Alias.ProtoReflect.Descriptor instead.
func (*Alias) Descriptor() ([]byte, []int) {
	return file_config_v1_config_proto_rawDescGZIP(), []int{24}
}

func (x *Alias) GetAlias() string {
	if x != nil {
		return x.Alias
	}
	return ""
}

func (x *Alias) GetTarget() string {
	if x != nil {
		return x.Target
	}
	return ""
}

func (x *Alias) GetVersion() int64 {
	if x != nil {
		return x.Version
	}
	return 0
}

func (x *Alias) GetCreatedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.CreatedAt
	}
	return nil
}

// Entry represents a configuration entry.
type Entry struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Namespace     string                 `protobuf:"bytes,1,opt,name=namespace,proto3" json:"namespace,omitempty"`
	Key           string                 `protobuf:"bytes,2,opt,name=key,proto3" json:"key,omitempty"`
	Value         []byte                 `protobuf:"bytes,3,opt,name=value,proto3" json:"value,omitempty"`
	Codec         string                 `protobuf:"bytes,4,opt,name=codec,proto3" json:"codec,omitempty"`
	Type          int32                  `protobuf:"varint,5,opt,name=type,proto3" json:"type,omitempty"` // config.Type enum value
	Version       int64                  `protobuf:"varint,6,opt,name=version,proto3" json:"version,omitempty"`
	CreatedAt     *timestamppb.Timestamp `protobuf:"bytes,7,opt,name=created_at,json=createdAt,proto3" json:"created_at,omitempty"`
	UpdatedAt     *timestamppb.Timestamp `protobuf:"bytes,8,opt,name=updated_at,json=updatedAt,proto3" json:"updated_at,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Entry) Reset() {
	*x = Entry{}
	mi := &file_config_v1_config_proto_msgTypes[25]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Entry) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Entry) ProtoMessage() {}

func (x *Entry) ProtoReflect() protoreflect.Message {
	mi := &file_config_v1_config_proto_msgTypes[25]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Entry.ProtoReflect.Descriptor instead.
func (*Entry) Descriptor() ([]byte, []int) {
	return file_config_v1_config_proto_rawDescGZIP(), []int{25}
}

func (x *Entry) GetNamespace() string {
	if x != nil {
		return x.Namespace
	}
	return ""
}

func (x *Entry) GetKey() string {
	if x != nil {
		return x.Key
	}
	return ""
}

func (x *Entry) GetValue() []byte {
	if x != nil {
		return x.Value
	}
	return nil
}

func (x *Entry) GetCodec() string {
	if x != nil {
		return x.Codec
	}
	return ""
}

func (x *Entry) GetType() int32 {
	if x != nil {
		return x.Type
	}
	return 0
}

func (x *Entry) GetVersion() int64 {
	if x != nil {
		return x.Version
	}
	return 0
}

func (x *Entry) GetCreatedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.CreatedAt
	}
	return nil
}

func (x *Entry) GetUpdatedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.UpdatedAt
	}
	return nil
}

var File_config_v1_config_proto protoreflect.FileDescriptor

const file_config_v1_config_proto_rawDesc = "" +
	"\n" +
	"\x16config/v1/config.proto\x12\tconfig.v1\x1a\x1cgoogle/api/annotations.proto\x1a\x1fgoogle/protobuf/timestamp.proto\"<\n" +
	"\n" +
	"GetRequest\x12\x1c\n" +
	"\tnamespace\x18\x01 \x01(\tR\tnamespace\x12\x10\n" +
	"\x03key\x18\x02 \x01(\tR\x03key\"5\n" +
	"\vGetResponse\x12&\n" +
	"\x05entry\x18\x01 \x01(\v2\x10.config.v1.EntryR\x05entry\"\x9d\x01\n" +
	"\n" +
	"SetRequest\x12\x1c\n" +
	"\tnamespace\x18\x01 \x01(\tR\tnamespace\x12\x10\n" +
	"\x03key\x18\x02 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x03 \x01(\fR\x05value\x12\x14\n" +
	"\x05codec\x18\x04 \x01(\tR\x05codec\x123\n" +
	"\n" +
	"write_mode\x18\x05 \x01(\x0e2\x14.config.v1.WriteModeR\twriteMode\"5\n" +
	"\vSetResponse\x12&\n" +
	"\x05entry\x18\x01 \x01(\v2\x10.config.v1.EntryR\x05entry\"?\n" +
	"\rDeleteRequest\x12\x1c\n" +
	"\tnamespace\x18\x01 \x01(\tR\tnamespace\x12\x10\n" +
	"\x03key\x18\x02 \x01(\tR\x03key\"\x10\n" +
	"\x0eDeleteResponse\"q\n" +
	"\vListRequest\x12\x1c\n" +
	"\tnamespace\x18\x01 \x01(\tR\tnamespace\x12\x16\n" +
	"\x06prefix\x18\x02 \x01(\tR\x06prefix\x12\x14\n" +
	"\x05limit\x18\x03 \x01(\x05R\x05limit\x12\x16\n" +
	"\x06cursor\x18\x04 \x01(\tR\x06cursor\"[\n" +
	"\fListResponse\x12*\n" +
	"\aentries\x18\x01 \x03(\v2\x10.config.v1.EntryR\aentries\x12\x1f\n" +
	"\vnext_cursor\x18\x02 \x01(\tR\n" +
	"nextCursor\"\x8c\x01\n" +
	"\x12GetVersionsRequest\x12\x1c\n" +
	"\tnamespace\x18\x01 \x01(\tR\tnamespace\x12\x10\n" +
	"\x03key\x18\x02 \x01(\tR\x03key\x12\x18\n" +
	"\aversion\x18\x03 \x01(\x03R\aversion\x12\x14\n" +
	"\x05limit\x18\x04 \x01(\x05R\x05limit\x12\x16\n" +
	"\x06cursor\x18\x05 \x01(\tR\x06cursor\"x\n" +
	"\x13GetVersionsResponse\x12*\n" +
	"\aentries\x18\x01 \x03(\v2\x10.config.v1.EntryR\aentries\x12\x1f\n" +
	"\vnext_cursor\x18\x02 \x01(\tR\n" +
	"nextCursor\x12\x14\n" +
	"\x05limit\x18\x03 \x01(\x05R\x05limit\"S\n" +
	"\x0fSnapshotRequest\x12\x1c\n" +
	"\tnamespace\x18\x01 \x01(\tR\tnamespace\x12\"\n" +
	"\rif_none_match\x18\x02 \x01(\tR\vifNoneMatch\"u\n" +
	"\x10SnapshotResponse\x12*\n" +
	"\aentries\x18\x01 \x03(\v2\x10.config.v1.EntryR\aentries\x12\x12\n" +
	"\x04etag\x18\x02 \x01(\tR\x04etag\x12!\n" +
	"\fnot_modified\x18\x03 \x01(\bR\vnotModified\"J\n" +
	"\fWatchRequest\x12\x1e\n" +
	"\n" +
	"namespaces\x18\x01 \x03(\tR\n" +
	"namespaces\x12\x1a\n" +
	"\bprefixes\x18\x02 \x03(\tR\bprefixes\"b\n" +
	"\rWatchResponse\x12)\n" +
	"\x04type\x18\x01 \x01(\x0e2\x15.config.v1.ChangeTypeR\x04type\x12&\n" +
	"\x05entry\x18\x02 \x01(\v2\x10.config.v1.EntryR\x05entry\"2\n" +
	"\x12CheckAccessRequest\x12\x1c\n" +
	"\tnamespace\x18\x01 \x01(\tR\tnamespace\"M\n" +
	"\x13CheckAccessResponse\x12\x19\n" +
	"\bcan_read\x18\x01 \x01(\bR\acanRead\x12\x1b\n" +
	"\tcan_write\x18\x02 \x01(\bR\bcanWrite\"?\n" +
	"\x0fSetAliasRequest\x12\x14\n" +
	"\x05alias\x18\x01 \x01(\tR\x05alias\x12\x16\n" +
	"\x06target\x18\x02 \x01(\tR\x06target\":\n" +
	"\x10SetAliasResponse\x12&\n" +
	"\x05alias\x18\x01 \x01(\v2\x10.config.v1.AliasR\x05alias\"*\n" +
	"\x12DeleteAliasRequest\x12\x14\n" +
	"\x05alias\x18\x01 \x01(\tR\x05alias\"\x15\n" +
	"\x13DeleteAliasResponse\"'\n" +
	"\x0fGetAliasRequest\x12\x14\n" +
	"\x05alias\x18\x01 \x01(\tR\x05alias\":\n" +
	"\x10GetAliasResponse\x12&\n" +
	"\x05alias\x18\x01 \x01(\v2\x10.config.v1.AliasR\x05alias\"\x14\n" +
	"\x12ListAliasesRequest\"A\n" +
	"\x13ListAliasesResponse\x12*\n" +
	"\aaliases\x18\x01 \x03(\v2\x10.config.v1.AliasR\aaliases\"\x8a\x01\n" +
	"\x05Alias\x12\x14\n" +
	"\x05alias\x18\x01 \x01(\tR\x05alias\x12\x16\n" +
	"\x06target\x18\x02 \x01(\tR\x06target\x12\x18\n" +
	"\aversion\x18\x03 \x01(\x03R\aversion\x129\n" +
	"\n" +
	"created_at\x18\x04 \x01(\v2\x1a.google.protobuf.TimestampR\tcreatedAt\"\x87\x02\n" +
	"\x05Entry\x12\x1c\n" +
	"\tnamespace\x18\x01 \x01(\tR\tnamespace\x12\x10\n" +
	"\x03key\x18\x02 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x03 \x01(\fR\x05value\x12\x14\n" +
	"\x05codec\x18\x04 \x01(\tR\x05codec\x12\x12\n" +
	"\x04type\x18\x05 \x01(\x05R\x04type\x12\x18\n" +
	"\aversion\x18\x06 \x01(\x03R\aversion\x129\n" +
	"\n" +
	"created_at\x18\a \x01(\v2\x1a.google.protobuf.TimestampR\tcreatedAt\x129\n" +
	"\n" +
	"updated_at\x18\b \x01(\v2\x1a.google.protobuf.TimestampR\tupdatedAt*l\n" +
	"\tWriteMode\x12\x1a\n" +
	"\x16WRITE_MODE_UNSPECIFIED\x10\x00\x12\x15\n" +
	"\x11WRITE_MODE_UPSERT\x10\x01\x12\x15\n" +
	"\x11WRITE_MODE_CREATE\x10\x02\x12\x15\n" +
	"\x11WRITE_MODE_UPDATE\x10\x03*\x8f\x01\n" +
	"\n" +
	"ChangeType\x12\x1b\n" +
	"\x17CHANGE_TYPE_UNSPECIFIED\x10\x00\x12\x13\n" +
	"\x0fCHANGE_TYPE_SET\x10\x01\x12\x16\n" +
	"\x12CHANGE_TYPE_DELETE\x10\x02\x12\x19\n" +
	"\x15CHANGE_TYPE_ALIAS_SET\x10\x03\x12\x1c\n" +
	"\x18CHANGE_TYPE_ALIAS_DELETE\x10\x042\xf1\t\n" +
	"\rConfigService\x12c\n" +
	"\x03Get\x12\x15.config.v1.GetRequest\x1a\x16.config.v1.GetResponse\"-\x82\xd3\xe4\x93\x02'\x12%/v1/namespaces/{namespace}/keys/{key}\x12f\n" +
	"\x03Set\x12\x15.config.v1.SetRequest\x1a\x16.config.v1.SetResponse\"0\x82\xd3\xe4\x93\x02*:\x01*\"%/v1/namespaces/{namespace}/keys/{key}\x12l\n" +
	"\x06Delete\x12\x18.config.v1.DeleteRequest\x1a\x19.config.v1.DeleteResponse\"-\x82\xd3\xe4\x93\x02'*%/v1/namespaces/{namespace}/keys/{key}\x12`\n" +
	"\x04List\x12\x16.config.v1.ListRequest\x1a\x17.config.v1.ListResponse\"'\x82\xd3\xe4\x93\x02!\x12\x1f/v1/namespaces/{namespace}/keys\x12\x84\x01\n" +
	"\vGetVersions\x12\x1d.config.v1.GetVersionsRequest\x1a\x1e.config.v1.GetVersionsResponse\"6\x82\xd3\xe4\x93\x020\x12./v1/namespaces/{namespace}/keys/{key}/versions\x12p\n" +
	"\bSnapshot\x12\x1a.config.v1.SnapshotRequest\x1a\x1b.config.v1.SnapshotResponse\"+\x82\xd3\xe4\x93\x02%\x12#/v1/namespaces/{namespace}/snapshot\x12<\n" +
	"\x05Watch\x12\x17.config.v1.WatchRequest\x1a\x18.config.v1.WatchResponse0\x01\x12w\n" +
	"\vCheckAccess\x12\x1d.config.v1.CheckAccessRequest\x1a\x1e.config.v1.CheckAccessResponse\")\x82\xd3\xe4\x93\x02#\x12!/v1/namespaces/{namespace}/access\x12c\n" +
	"\bSetAlias\x12\x1a.config.v1.SetAliasRequest\x1a\x1b.config.v1.SetAliasResponse\"\x1e\x82\xd3\xe4\x93\x02\x18:\x01*\x1a\x13/v1/aliases/{alias}\x12i\n" +
	"\vDeleteAlias\x12\x1d.config.v1.DeleteAliasRequest\x1a\x1e.config.v1.DeleteAliasResponse\"\x1b\x82\xd3\xe4\x93\x02\x15*\x13/v1/aliases/{alias}\x12`\n" +
	"\bGetAlias\x12\x1a.config.v1.GetAliasRequest\x1a\x1b.config.v1.GetAliasResponse\"\x1b\x82\xd3\xe4\x93\x02\x15\x12\x13/v1/aliases/{alias}\x12a\n" +
	"\vListAliases\x12\x1d.config.v1.ListAliasesRequest\x1a\x1e.config.v1.ListAliasesResponse\"\x13\x82\xd3\xe4\x93\x02\r\x12\v/v1/aliasesB<Z:github.com/rbaliyan/config-server/proto/config/v1;configpbb\x06proto3"

var (
	file_config_v1_config_proto_rawDescOnce sync.Once
	file_config_v1_config_proto_rawDescData []byte
)

func file_config_v1_config_proto_rawDescGZIP() []byte {
	file_config_v1_config_proto_rawDescOnce.Do(func() {
		file_config_v1_config_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_config_v1_config_proto_rawDesc), len(file_config_v1_config_proto_rawDesc)))
	})
	return file_config_v1_config_proto_rawDescData
}

var file_config_v1_config_proto_enumTypes = make([]protoimpl.EnumInfo, 2)
var file_config_v1_config_proto_msgTypes = make([]protoimpl.MessageInfo, 26)
var file_config_v1_config_proto_goTypes = []any{
	(WriteMode)(0),                // 0: config.v1.WriteMode
	(ChangeType)(0),               // 1: config.v1.ChangeType
	(*GetRequest)(nil),            // 2: config.v1.GetRequest
	(*GetResponse)(nil),           // 3: config.v1.GetResponse
	(*SetRequest)(nil),            // 4: config.v1.SetRequest
	(*SetResponse)(nil),           // 5: config.v1.SetResponse
	(*DeleteRequest)(nil),         // 6: config.v1.DeleteRequest
	(*DeleteResponse)(nil),        // 7: config.v1.DeleteResponse
	(*ListRequest)(nil),           // 8: config.v1.ListRequest
	(*ListResponse)(nil),          // 9: config.v1.ListResponse
	(*GetVersionsRequest)(nil),    // 10: config.v1.GetVersionsRequest
	(*GetVersionsResponse)(nil),   // 11: config.v1.GetVersionsResponse
	(*SnapshotRequest)(nil),       // 12: config.v1.SnapshotRequest
	(*SnapshotResponse)(nil),      // 13: config.v1.SnapshotResponse
	(*WatchRequest)(nil),          // 14: config.v1.WatchRequest
	(*WatchResponse)(nil),         // 15: config.v1.WatchResponse
	(*CheckAccessRequest)(nil),    // 16: config.v1.CheckAccessRequest
	(*CheckAccessResponse)(nil),   // 17: config.v1.CheckAccessResponse
	(*SetAliasRequest)(nil),       // 18: config.v1.SetAliasRequest
	(*SetAliasResponse)(nil),      // 19: config.v1.SetAliasResponse
	(*DeleteAliasRequest)(nil),    // 20: config.v1.DeleteAliasRequest
	(*DeleteAliasResponse)(nil),   // 21: config.v1.DeleteAliasResponse
	(*GetAliasRequest)(nil),       // 22: config.v1.GetAliasRequest
	(*GetAliasResponse)(nil),      // 23: config.v1.GetAliasResponse
	(*ListAliasesRequest)(nil),    // 24: config.v1.ListAliasesRequest
	(*ListAliasesResponse)(nil),   // 25: config.v1.ListAliasesResponse
	(*Alias)(nil),                 // 26: config.v1.Alias
	(*Entry)(nil),                 // 27: config.v1.Entry
	(*timestamppb.Timestamp)(nil), // 28: google.protobuf.Timestamp
}
var file_config_v1_config_proto_depIdxs = []int32{
	27, // 0: config.v1.GetResponse.entry:type_name -> config.v1.Entry
	0,  // 1: config.v1.SetRequest.write_mode:type_name -> config.v1.WriteMode
	27, // 2: config.v1.SetResponse.entry:type_name -> config.v1.Entry
	27, // 3: config.v1.ListResponse.entries:type_name -> config.v1.Entry
	27, // 4: config.v1.GetVersionsResponse.entries:type_name -> config.v1.Entry
	27, // 5: config.v1.SnapshotResponse.entries:type_name -> config.v1.Entry
	1,  // 6: config.v1.WatchResponse.type:type_name -> config.v1.ChangeType
	27, // 7: config.v1.WatchResponse.entry:type_name -> config.v1.Entry
	26, // 8: config.v1.SetAliasResponse.alias:type_name -> config.v1.Alias
	26, // 9: config.v1.GetAliasResponse.alias:type_name -> config.v1.Alias
	26, // 10: config.v1.ListAliasesResponse.aliases:type_name -> config.v1.Alias
	28, // 11: config.v1.Alias.created_at:type_name -> google.protobuf.Timestamp
	28, // 12: config.v1.Entry.created_at:type_name -> google.protobuf.Timestamp
	28, // 13: config.v1.Entry.updated_at:type_name -> google.protobuf.Timestamp
	2,  // 14: config.v1.ConfigService.Get:input_type -> config.v1.GetRequest
	4,  // 15: config.v1.ConfigService.Set:input_type -> config.v1.SetRequest
	6,  // 16: config.v1.ConfigService.Delete:input_type -> config.v1.DeleteRequest
	8,  // 17: config.v1.ConfigService.List:input_type -> config.v1.ListRequest
	10, // 18: config.v1.ConfigService.GetVersions:input_type -> config.v1.GetVersionsRequest
	12, // 19: config.v1.ConfigService.Snapshot:input_type -> config.v1.SnapshotRequest
	14, // 20: config.v1.ConfigService.Watch:input_type -> config.v1.WatchRequest
	16, // 21: config.v1.ConfigService.CheckAccess:input_type -> config.v1.CheckAccessRequest
	18, // 22: config.v1.ConfigService.SetAlias:input_type -> config.v1.SetAliasRequest
	20, // 23: config.v1.ConfigService.DeleteAlias:input_type -> config.v1.DeleteAliasRequest
	22, // 24: config.v1.ConfigService.GetAlias:input_type -> config.v1.GetAliasRequest
	24, // 25: config.v1.ConfigService.ListAliases:input_type -> config.v1.ListAliasesRequest
	3,  // 26: config.v1.ConfigService.Get:output_type -> config.v1.GetResponse
	5,  // 27: config.v1.ConfigService.Set:output_type -> config.v1.SetResponse
	7,  // 28: config.v1.ConfigService.Delete:output_type -> config.v1.DeleteResponse
	9,  // 29: config.v1.ConfigService.List:output_type -> config.v1.ListResponse
	11, // 30: config.v1.ConfigService.GetVersions:output_type -> config.v1.GetVersionsResponse
	13, // 31: config.v1.ConfigService.Snapshot:output_type -> config.v1.SnapshotResponse
	15, // 32: config.v1.ConfigService.Watch:output_type -> config.v1.WatchResponse
	17, // 33: config.v1.ConfigService.CheckAccess:output_type -> config.v1.CheckAccessResponse
	19, // 34: config.v1.ConfigService.SetAlias:output_type -> config.v1.SetAliasResponse
	21, // 35: config.v1.ConfigService.DeleteAlias:output_type -> config.v1.DeleteAliasResponse
	23, // 36: config.v1.ConfigService.GetAlias:output_type -> config.v1.GetAliasResponse
	25, // 37: config.v1.ConfigService.ListAliases:output_type -> config.v1.ListAliasesResponse
	26, // [26:38] is the sub-list for method output_type
	14, // [14:26] is the sub-list for method input_type
	14, // [14:14] is the sub-list for extension type_name
	14, // [14:14] is the sub-list for extension extendee
	0,  // [0:14] is the sub-list for field type_name
}

func init() { file_config_v1_config_proto_init() }
func file_config_v1_config_proto_init() {
	if File_config_v1_config_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_config_v1_config_proto_rawDesc), len(file_config_v1_config_proto_rawDesc)),
			NumEnums:      2,
			NumMessages:   26,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_config_v1_config_proto_goTypes,
		DependencyIndexes: file_config_v1_config_proto_depIdxs,
		EnumInfos:         file_config_v1_config_proto_enumTypes,
		MessageInfos:      file_config_v1_config_proto_msgTypes,
	}.Build()
	File_config_v1_config_proto = out.File
	file_config_v1_config_proto_goTypes = nil
	file_config_v1_config_proto_depIdxs = nil
}
